//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexiNetV2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LexiNetDbEntities2 : DbContext
    {
        public LexiNetDbEntities2()
            : base("name=LexiNetDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FeedbackTbl> FeedbackTbls { get; set; }
        public virtual DbSet<ResourcesTbl> ResourcesTbls { get; set; }
        public virtual DbSet<UserTbl> UserTbls { get; set; }
    }
}
