//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexiNetV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourcesTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResourcesTbl()
        {
            this.FeedbackTbls = new HashSet<FeedbackTbl>();
        }
    
        public int resourceID { get; set; }
        public string resourceName { get; set; }
        public string resourceType { get; set; }
        public Nullable<int> userID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackTbl> FeedbackTbls { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
